# EXERCICE P03

CXX = g++
CC  = $(CXX)

CXXFLAGS = -std=c++11
CXXFLAGS += -g

all:: exercice_p03

vecteur.o: vecteur.cpp vecteur.h

exercice_p03.o: exercice_p03.cpp vecteur.h

exercice_p03: exercice_p03.o vecteur.o